# Generated by Django 4.1.5 on 2023-01-17 12:05

from django.db import migrations, models

sig_str = (""" Written by TSC. 
           Enough turbulent meaninglessness creates purpose - Cixin Liu""")
class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='signature',
            field=models.CharField(default="TSC \n 'Enough turbulent meaninglessness creates purpose' - Cixin Liu", max_length=140),
        ),
    ]
