# Generated by Django 4.1.5 on 2023-01-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='signature',
            field=models.CharField(default=' Written by TSC. \n           Enough turbulent meaninglessness creates purpose - Cixin Liu', max_length=140),
        ),
    ]
