# Generated by Django 4.1.5 on 2023-02-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='signature',
        ),
        migrations.AddField(
            model_name='post',
            name='works_cited',
            field=models.TextField(default='No Works Cited'),
        ),
    ]
