version: '3'

services: 
  capstone:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: capstone:django
    container_name: django_container 
    command: python manage.py runserver 0.0.0.0:8000