version: '3'

services: 
  hyperion:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: hyperion:django
    container_name: django_container1
    command: python manage.py runserver 0.0.0.0:8000